name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:

  format:
    name: Check code format (rye)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2

      - name: Run linting
        run: rye run formatcheck

  lint:
    name: Check code quality (rye)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2

      - name: Run linting
        run: rye run lint

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          cache-prefix: 'bench'

      - name: Install project
        run: rye run bootstrap

      - name: Run benchmarks
        run: rye run bench

  test_and_coverage:
    name: Tests 3.10 with coverage (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          cache-prefix: 'test-3.10'

      - name: Run pytest
        run: rye run ci-test

  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      # Uses the same action as rye
      # See: https://github.com/astral-sh/rye/blob/main/.github/workflows/python-lint.yml
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          cache-prefix: 'test-${{ matrix.python-version }}'

      - name: Override python version required by project
        run: |
          echo "${{ matrix.python-version }}" > .python-version

      - name: Run pytest
        run: rye run ci-test-without-coverage

  typecheck:
    name: Typecheck (pyright)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      # Uses the same action as rye
      # See: https://github.com/astral-sh/rye/blob/main/.github/workflows/python-lint.yml
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          cache-prefix: 'typecheck-${{ matrix.python-version }}'

      - name: Override python version required by project
        run: |
          echo "${{ matrix.python-version }}" > .python-version
          sed -i -e 's/pythonVersion = "3.10"/pythonVersion = "${{ matrix.python-version }}"/g' pyproject.toml

      - name: Run validation
        run: rye run ci-typecheck
